export DB_USER=postgres
export DB_PASS=pgpass
export DB_NAME=postgres
export GOOGLE_TOKEN_AUDIENCE="<oauth-client-id>.apps.googleusercontent.com"
export INSTANCE_UNIX_SOCKET=localhost
export TOKEN_VALID_MINUTES=60
export REFRESH_TOKEN_VALID_MINUTES=240
export TOKEN_GRACE_SECONDS=20
export ALLOWED_ORIGIN=http://localhost
read -r -d '' PK << EOM
-----BEGIN RSA PRIVATE KEY-----
<a private key generated by you to sign tokens>
-----END RSA PRIVATE KEY-----
EOM
export PRIVATE_KEY=$PK
read -r -d '' PUBK << EOM
-----BEGIN PUBLIC KEY-----
<your public key.  Used to verify token signatures>
-----END PUBLIC KEY-----
EOM
export PUBLIC_KEY=$PUBK
go build .
./goapi --debug=true --log_to_console=true